spring:
  application:
    name: PdfSorgu
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: REQUIRE_MODEL_PROFILE_BY_JAR_ARGUMENT

  datasource:
    url: jdbc:postgresql://localhost:5432/pdfsorgu-db
    username: userpgv
    password: passpgv
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

#logging:
#  level:
#    org.springframework.web: ERROR

server:
  servlet:
    session:
      timeout: 60000
  tomcat:
    connection-timeout: 60000

file:
  upload-dir: uploads

api:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration-seconds: 600